export const LOAD_ALL_GAMES = "LOAD_ALL_GAMES";
export const LOAD_ALL_GAMES_ATTEMPT = "LOAD_ALL_GAMES_ATTEMPT";
export const LOAD_ALL_GAMES_SUCCESS = "LOAD_ALL_GAMES_SUCCESS";
export const LOAD_ALL_GAMES_FAIL = "LOAD_ALL_GAMES_FAIL";
